name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 146.103.102.75          # тут твой IP VPS
          username: deploy              # юзер
          key: ${{ secrets.SSH_KEY }}   # приватный ключ берём из секретов
          script: |
            cd /home/deploy/media-parser-bot
            git pull
            docker build -t bot .
            docker run -d --rm --name bot_vps bot   
